import { DOCUMENT_KIND, EDGE_TYPE, NODE_KIND } from "./document.ts";

type DocumentKind = (typeof DOCUMENT_KIND)[keyof typeof DOCUMENT_KIND];
type EdgeType = (typeof EDGE_TYPE)[keyof typeof EDGE_TYPE];
type NodeKind = (typeof NODE_KIND)[keyof typeof NODE_KIND];

export const NODES_FOR_KIND: Record<DocumentKind, readonly NodeKind[]> = {
  [DOCUMENT_KIND.ARCHITECTURE]: [
    NODE_KIND.SERVICE,
    NODE_KIND.DATASTORE,
    NODE_KIND.QUEUE,
    NODE_KIND.GATEWAY,
    NODE_KIND.ACTOR,
    NODE_KIND.SYSTEM,
    NODE_KIND.JOB,
    NODE_KIND.EXTERNAL,
  ],
  [DOCUMENT_KIND.WORKFLOW]: [
    NODE_KIND.ACTOR,
    NODE_KIND.JOB,
    NODE_KIND.DECISION,
    NODE_KIND.SYSTEM,
    NODE_KIND.GATEWAY,
  ],
  [DOCUMENT_KIND.SEQUENCE]: [NODE_KIND.PARTICIPANT, NODE_KIND.ACTOR],
  [DOCUMENT_KIND.DATA_FLOW]: [
    NODE_KIND.PROCESS,
    NODE_KIND.DATASTORE,
    NODE_KIND.ENTITY,
    NODE_KIND.EXTERNAL,
  ],
  [DOCUMENT_KIND.LIFECYCLE]: [NODE_KIND.STATE],
};

export const EDGES_FOR_KIND: Record<DocumentKind, readonly EdgeType[]> = {
  [DOCUMENT_KIND.ARCHITECTURE]: [
    EDGE_TYPE.CALLS,
    EDGE_TYPE.READS,
    EDGE_TYPE.WRITES,
    EDGE_TYPE.PUBLISHES,
    EDGE_TYPE.SUBSCRIBES,
    EDGE_TYPE.DEPENDS_ON,
  ],
  [DOCUMENT_KIND.WORKFLOW]: [EDGE_TYPE.CALLS, EDGE_TYPE.OUTCOME],
  [DOCUMENT_KIND.SEQUENCE]: [EDGE_TYPE.MESSAGE, EDGE_TYPE.REPLY],
  [DOCUMENT_KIND.DATA_FLOW]: [EDGE_TYPE.DATA, EDGE_TYPE.READS, EDGE_TYPE.WRITES],
  [DOCUMENT_KIND.LIFECYCLE]: [EDGE_TYPE.TRANSITION],
};

export function defaultEdgeType(kind: DocumentKind): EdgeType {
  if (kind === DOCUMENT_KIND.SEQUENCE) return EDGE_TYPE.MESSAGE;
  if (kind === DOCUMENT_KIND.DATA_FLOW) return EDGE_TYPE.DATA;
  if (kind === DOCUMENT_KIND.LIFECYCLE) return EDGE_TYPE.TRANSITION;
  if (kind === DOCUMENT_KIND.WORKFLOW) return EDGE_TYPE.CALLS;
  return EDGE_TYPE.CALLS;
}
