export const OPERATION_KIND = {
  SET_TITLE: "set_title",
  SET_NODE_LABEL: "set_node_label",
  SET_GROUP_LABEL: "set_group_label",
  SET_EDGE_LABEL: "set_edge_label",
  SET_EDGE_TYPE: "set_edge_type",
  SET_EDGE_DIRECTION: "set_edge_direction",
  SET_EDGE_ORDER: "set_edge_order",
  SET_EDGE_GUARD: "set_edge_guard",
  SET_EDGE_OUTCOME: "set_edge_outcome",
  SET_NODE_KIND: "set_node_kind",
  SET_NODE_MARKER: "set_node_marker",
  ADD_NODE: "add_node",
  ADD_EDGE: "add_edge",
  DELETE_NODE: "delete_node",
  DELETE_EDGE: "delete_edge",
  DUPLICATE_NODE: "duplicate_node",
  SET_NODE_GROUP: "set_node_group",
  SET_NODE_PINNED: "set_node_pinned",
  SET_LAYOUT: "set_layout",
  SET_THEME: "set_theme",
  SET_DOCUMENT_KIND: "set_document_kind",
  ADD_GROUP: "add_group",
  DELETE_GROUP: "delete_group",
} as const;
