import { DOCUMENT_KIND, EDGE_TYPE, NODE_KIND } from "@mapgrain/document";
import { TEMPLATE_CATEGORY } from "../../constants/templates.ts";
import type { TemplateSpec } from "../../types/templates.ts";
import { template } from "../build.ts";

const category = TEMPLATE_CATEGORY.ARCHITECTURE;
const kind = DOCUMENT_KIND.ARCHITECTURE;

export const ARCHITECTURE_TEMPLATES: TemplateSpec[] = [
  {
    id: "c4-context",
    category,
    title: "System context",
    blurb: "One system, the people who use it and the systems it depends on.",
    tags: ["c4", "context", "overview"],
    document: template({
      id: "tpl-c4-context",
      title: "System context",
      kind,
      viewName: "Context",
      nodes: [
        { id: "customer", kind: NODE_KIND.ACTOR, label: "Customer", at: [0, 1] },
        { id: "support", kind: NODE_KIND.ACTOR, label: "Support agent", at: [0, 2] },
        { id: "platform", kind: NODE_KIND.SYSTEM, label: "Booking platform", at: [1, 1] },
        { id: "payments", kind: NODE_KIND.EXTERNAL, label: "Payment provider", at: [2, 0] },
        { id: "email", kind: NODE_KIND.EXTERNAL, label: "Email provider", at: [2, 1] },
        { id: "crm", kind: NODE_KIND.EXTERNAL, label: "CRM", at: [2, 2] },
      ],
      edges: [
        { from: "customer", to: "platform", label: "books and pays" },
        { from: "support", to: "platform", label: "resolves bookings" },
        { from: "platform", to: "payments", label: "takes payment" },
        { from: "platform", to: "email", label: "sends confirmations" },
        { from: "platform", to: "crm", type: EDGE_TYPE.PUBLISHES, label: "customer events" },
      ],
    }),
  },
  {
    id: "c4-container",
    category,
    title: "Containers",
    blurb: "The deployable pieces inside one system and the stores they own.",
    tags: ["c4", "container", "services"],
    document: template({
      id: "tpl-c4-container",
      title: "Containers",
      kind,
      viewName: "Containers",
      groups: [{ id: "platform", label: "Booking platform" }],
      nodes: [
        { id: "customer", kind: NODE_KIND.ACTOR, label: "Customer", at: [0, 1] },
        { id: "web", kind: NODE_KIND.SYSTEM, label: "Web app", group: "platform", at: [1, 0] },
        { id: "mobile", kind: NODE_KIND.SYSTEM, label: "Mobile app", group: "platform", at: [1, 2] },
        { id: "api", kind: NODE_KIND.GATEWAY, label: "Booking API", group: "platform", at: [2, 1] },
        { id: "worker", kind: NODE_KIND.JOB, label: "Settlement worker", group: "platform", at: [3, 2] },
        { id: "db", kind: NODE_KIND.DATASTORE, label: "Booking database", group: "platform", at: [3, 0] },
        { id: "queue", kind: NODE_KIND.QUEUE, label: "Settlement queue", group: "platform", at: [3, 1] },
      ],
      edges: [
        { from: "customer", to: "web", label: "uses" },
        { from: "customer", to: "mobile", label: "uses" },
        { from: "web", to: "api", label: "JSON over HTTPS" },
        { from: "mobile", to: "api", label: "JSON over HTTPS" },
        { from: "api", to: "db", type: EDGE_TYPE.WRITES, label: "bookings" },
        { from: "api", to: "queue", type: EDGE_TYPE.PUBLISHES, label: "booking.confirmed" },
        { from: "worker", to: "queue", type: EDGE_TYPE.SUBSCRIBES, label: "booking.confirmed" },
        { from: "worker", to: "db", type: EDGE_TYPE.WRITES, label: "settlement" },
      ],
    }),
  },
  {
    id: "microservices",
    category,
    title: "Microservices behind a gateway",
    blurb: "An edge gateway, the services behind it and the store each one owns.",
    tags: ["microservices", "gateway", "services"],
    document: template({
      id: "tpl-microservices",
      title: "Microservices behind a gateway",
      kind,
      viewName: "Services",
      nodes: [
        { id: "client", kind: NODE_KIND.ACTOR, label: "Client", at: [0, 1] },
        { id: "gateway", kind: NODE_KIND.GATEWAY, label: "API gateway", at: [1, 1] },
        { id: "identity", kind: NODE_KIND.SERVICE, label: "Identity", at: [2, 0] },
        { id: "catalog", kind: NODE_KIND.SERVICE, label: "Catalog", at: [2, 1] },
        { id: "orders", kind: NODE_KIND.SERVICE, label: "Orders", at: [2, 2] },
        { id: "catalogdb", kind: NODE_KIND.DATASTORE, label: "Catalog store", at: [3, 1] },
        { id: "ordersdb", kind: NODE_KIND.DATASTORE, label: "Order store", at: [3, 2] },
        { id: "events", kind: NODE_KIND.QUEUE, label: "Domain events", at: [3, 3] },
      ],
      edges: [
        { from: "client", to: "gateway", label: "HTTPS" },
        { from: "gateway", to: "identity", label: "verifies token" },
        { from: "gateway", to: "catalog" },
        { from: "gateway", to: "orders" },
        { from: "catalog", to: "catalogdb", type: EDGE_TYPE.READS },
        { from: "orders", to: "ordersdb", type: EDGE_TYPE.WRITES },
        { from: "orders", to: "events", type: EDGE_TYPE.PUBLISHES, label: "order.placed" },
        { from: "catalog", to: "events", type: EDGE_TYPE.SUBSCRIBES, label: "order.placed" },
      ],
    }),
  },
  {
    id: "deployment",
    category,
    title: "Deployment topology",
    blurb: "What runs where, from the edge through each zone to the managed services.",
    tags: ["deployment", "infrastructure", "cloud"],
    document: template({
      id: "tpl-deployment",
      title: "Deployment topology",
      kind,
      viewName: "Topology",
      groups: [
        { id: "edge", label: "Edge" },
        { id: "cluster", label: "Cluster" },
        { id: "managed", label: "Managed services" },
      ],
      nodes: [
        { id: "user", kind: NODE_KIND.ACTOR, label: "User", at: [0, 1] },
        { id: "cdn", kind: NODE_KIND.EXTERNAL, label: "CDN", group: "edge", at: [1, 0] },
        { id: "lb", kind: NODE_KIND.GATEWAY, label: "Load balancer", group: "edge", at: [1, 1] },
        { id: "web", kind: NODE_KIND.SERVICE, label: "Web pods", group: "cluster", at: [2, 0] },
        { id: "api", kind: NODE_KIND.SERVICE, label: "API pods", group: "cluster", at: [2, 1] },
        { id: "jobs", kind: NODE_KIND.JOB, label: "Job runners", group: "cluster", at: [2, 2] },
        { id: "pg", kind: NODE_KIND.DATASTORE, label: "Managed Postgres", group: "managed", at: [3, 1] },
        { id: "objects", kind: NODE_KIND.DATASTORE, label: "Object storage", group: "managed", at: [3, 2] },
      ],
      edges: [
        { from: "user", to: "cdn", label: "static assets" },
        { from: "user", to: "lb", label: "HTTPS" },
        { from: "lb", to: "web" },
        { from: "lb", to: "api" },
        { from: "web", to: "api", label: "server render" },
        { from: "api", to: "pg", type: EDGE_TYPE.WRITES },
        { from: "jobs", to: "pg", type: EDGE_TYPE.READS },
        { from: "jobs", to: "objects", type: EDGE_TYPE.WRITES, label: "exports" },
      ],
    }),
  },
  {
    id: "rbac",
    category,
    title: "Roles and permissions",
    blurb: "Which role reaches which resource, and through which check.",
    tags: ["rbac", "permissions", "authorization"],
    document: template({
      id: "tpl-rbac",
      title: "Roles and permissions",
      kind,
      viewName: "Access",
      groups: [
        { id: "roles", label: "Roles" },
        { id: "resources", label: "Resources" },
      ],
      nodes: [
        { id: "viewer", kind: NODE_KIND.ACTOR, label: "Viewer", group: "roles", at: [0, 0] },
        { id: "editor", kind: NODE_KIND.ACTOR, label: "Editor", group: "roles", at: [0, 1] },
        { id: "admin", kind: NODE_KIND.ACTOR, label: "Admin", group: "roles", at: [0, 2] },
        { id: "policy", kind: NODE_KIND.GATEWAY, label: "Policy check", at: [1, 1] },
        { id: "docs", kind: NODE_KIND.DATASTORE, label: "Documents", group: "resources", at: [2, 0] },
        { id: "settings", kind: NODE_KIND.DATASTORE, label: "Workspace settings", group: "resources", at: [2, 1] },
        { id: "billing", kind: NODE_KIND.DATASTORE, label: "Billing", group: "resources", at: [2, 2] },
      ],
      edges: [
        { from: "viewer", to: "policy", label: "read" },
        { from: "editor", to: "policy", label: "read, write" },
        { from: "admin", to: "policy", label: "read, write, manage" },
        { from: "policy", to: "docs", type: EDGE_TYPE.READS, label: "any role" },
        { from: "policy", to: "settings", type: EDGE_TYPE.WRITES, label: "editor and admin" },
        { from: "policy", to: "billing", type: EDGE_TYPE.WRITES, label: "admin only" },
      ],
    }),
  },
  {
    id: "threat-model",
    category,
    title: "Trust boundaries",
    blurb: "What crosses each boundary, so the checks have somewhere to live.",
    tags: ["threat model", "security", "boundaries"],
    document: template({
      id: "tpl-threat-model",
      title: "Trust boundaries",
      kind,
      viewName: "Boundaries",
      groups: [
        { id: "untrusted", label: "Untrusted" },
        { id: "dmz", label: "Public edge" },
        { id: "internal", label: "Internal network" },
      ],
      nodes: [
        { id: "visitor", kind: NODE_KIND.ACTOR, label: "Anonymous visitor", group: "untrusted", at: [0, 0] },
        { id: "attacker", kind: NODE_KIND.EXTERNAL, label: "Untrusted input", group: "untrusted", at: [0, 1] },
        { id: "waf", kind: NODE_KIND.GATEWAY, label: "WAF and rate limit", group: "dmz", at: [1, 0] },
        { id: "authn", kind: NODE_KIND.SERVICE, label: "Authentication", group: "dmz", at: [1, 1] },
        { id: "app", kind: NODE_KIND.SERVICE, label: "Application", group: "internal", at: [2, 0] },
        { id: "secrets", kind: NODE_KIND.DATASTORE, label: "Secret store", group: "internal", at: [2, 2] },
        { id: "db", kind: NODE_KIND.DATASTORE, label: "Customer data", group: "internal", at: [2, 1] },
      ],
      edges: [
        { from: "visitor", to: "waf", label: "public traffic" },
        { from: "attacker", to: "waf", label: "hostile traffic" },
        { from: "waf", to: "authn", label: "filtered" },
        { from: "authn", to: "app", label: "session" },
        { from: "app", to: "db", type: EDGE_TYPE.READS, label: "scoped to tenant" },
        { from: "app", to: "secrets", type: EDGE_TYPE.READS, label: "short-lived lease" },
      ],
    }),
  },
];
